### ISSUE TITLE
Bartworks fails to run with runObfClient

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/RetroFuturaGradle#39]
Bartworks fails to launch with both `runObfClient` and `runObfServer`. The normal run tasks work. 

Steps to reproduce: Clone bartworks, update BS and dependencies, then run either obfuscated run task.

Error:
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 7/9/23 5:30 PM
Description: Initializing game

java.lang.NoClassDefFoundError: gregtech/api/enums/Mods
	at com.github.bartimaeusnek.bartworks.ASM.BWCore.getDependants(BWCore.java:75)
	at com.github.bartimaeusnek.bartworks.ASM.BWCore.<init>(BWCore.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:340)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: gregtech.api.enums.Mods
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 19 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.bartimaeusnek.bartworks.ASM.BWCore.getDependants(BWCore.java:75)
	at com.github.bartimaeusnek.bartworks.ASM.BWCore.<init>(BWCore.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:340)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 6.4.1-zen2-1-zen
	Java Version: 1.8.0_362, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 905480968 bytes (863 MB) / 1204813824 bytes (1149 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms1G -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		appliedenergistics2-core{rv3-beta-228-GTNH} [Applied Energistics 2 Core] (minecraft.jar) 
		CodeChickenCore{1.1.11} [CodeChicken Core] (minecraft.jar) 
		NotEnoughItems{2.3.55-GTNH} [NotEnoughItems] (NotEnoughItems-2.3.55-GTNH.jar) 
		<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.6 (Compatibility Profile) Mesa 23.1.3' Renderer: 'Mesa Intel(R) Graphics (ADL GT2)'
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: Mesa Intel(R) Graphics (ADL GT2) GL version 4.6 (Compatibility Profile) Mesa 23.1.3, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by bombcar** [comment]
I played around with this - it's because it doesn't even try to load GT5u, so something in the dependencies is sus, though runClient works, and the obfuscated/mods directory has stuff in it, both .jar and dev.jar

**Comment by eigenraven** [comment]
I don't think this issue is relevant anymore, closing as stale
